version: 0.1

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands: 
      - echo "Meta data about the environment"
      - which mvn
      - mvn -version
      - pwd
  build:
    commands:
      - echo "Building"
      - mvn package
  post_build:
    commands:
      - echo "Build Complete"
      - mkdir appfiles
      - cd appfiles
      - cp ../target/myproject-1.war .
      - cp ../appspec.yml .
      - tar -zcvf ../target/MyProject.tar.gx *.*
      - cd ..
artifacts:
  files:
    - appfiles/appspec.yml
    - appfiles/myproject-1.war
  discard-paths: yes

